import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthContext from '@/lib/context/AuthContext'
import  { ToastProvider } from '@/lib/context/ToasterContext'

import { getCurrentUser } from './actions/getCurrentUser'

import { Roledialogue } from '@/components/role-page/role-dialogue' 


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'lms',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const user = await getCurrentUser()
  let role;
  if(user){
   role = user.role;
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          <ToastProvider/>
          {role && user && children}
          {!role && user && <Roledialogue/>}
          {!role && !user && children}
        </AuthContext>
        </body>
    </html>
  )
}
