import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthContext from '@/lib/context/AuthContext'
import  { ToastProvider } from '@/lib/context/ToasterContext'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'lms',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          <ToastProvider/>
          {children}
        </AuthContext>
        </body>
    </html>
  )
}
